// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccuyiysnbejktmandjru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjdXlpeXNuYmVqa3RtYW5kanJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTYyNzcsImV4cCI6MjA2MTM3MjI3N30.0DA2Mlod5I_WzfB9yvNELxrfe7mYsQNFg0Tb1hBWUKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);